Volunteering offer fixes
CommuniBee/CommuniBee-Back-End pull request #28
Opened 2019-02-04 14:29 UTC by abrabing

2019-02-04 14:36 UTC, OrBin requested changes

2019-02-04 14:36 UTC, OrBin commented on models/volunteering-request-offer-base.js
>      type: [String],
Shouldn't it be `[Region]`?

2019-02-04 14:36 UTC, OrBin commented on routes/contents.js
> +const Category = require('../models/category').default;
Doesn't it work without `.default`? I'm pretty sure it should.

2019-02-04 14:53 UTC, OrBin commented
Also, fix the build error. It has an error when compiling the typescript code: https://travis-ci.org/CommuniBee/CommuniBee-Front-End/jobs/488525371#L536

2019-02-04 15:22 UTC, abrabing commented on models/volunteering-request-offer-base.js
>      type: [String],
It should be subregion

2019-02-05 07:20 UTC, OrBin requested changes

2019-02-05 07:20 UTC, OrBin commented on models/volunteering-request-offer-base.js
> +    type: ['SubRegion'],
Does it work like that?
From a short search (and the little exprience I've had with mongoose), I think it should look like:
```js
regions: {
  type: [
    {
      type: Schema.ObjectId,
      ref: 'Choices'
    }
  ],
  required: true,
},
```

2019-02-05 08:36 UTC, OrBin approved these changes

2019-02-05 08:48 UTC, merged